name: Trigger Spacelift

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-spacelift:
    runs-on: ubuntu-latest
    steps:
      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main
      
      - name: Trigger run
        env:
          SPACELIFT_API_KEY_ENDPOINT: https://shilu-new.app.spacelift.io
          SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_KEY_ID }}
          SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_KEY_SECRET }}
        run: spacectl stack deploy --id new-demo
